import type { DocumentFileType } from '@/shared/types/database'

/**
 * UX-14.5.10.3.1 — the manifest entry (`manifest.json`) inside a Document
 * export `.zip` (see `documentPackageArchive.ts` for the archive itself).
 * Allow-list, matching every other package type's own discipline: only
 * the fields listed here can ever leave a document in a package.
 * Deliberately excludes `id`, `user_id`, `workspace_id`, `collection_id`,
 * `file_path` (the internal storage reference — never trusted or reused
 * on import; a fresh path is always generated by `uploadDocument`), and
 * `status` (operational, not content).
 *
 * `tags` carries tag *names* only, re-resolved (find-or-create) in the
 * importing account, exactly like Notes'/Knowledge Nodes' own `tags`
 * field — never a reference to the exporter's own `tags.id`.
 *
 * Highlights deliberately don't appear here yet — UX-14.5.10.3.1 proves
 * the ZIP container format itself (export + validation only, per this
 * phase's explicit scope); highlights are UX-14.5.10.3.3's own,
 * separately-scoped addition, per
 * `docs/ux-14.5.10.3-document-exchange-discovery.md`'s phased roadmap
 * (§9).
 */
export interface DocumentPackagePayload {
  title: string
  fileName: string
  fileType: DocumentFileType
  sizeBytes: number
  createdAt: string
  tags: string[]
}

export interface DocumentPackageManifest {
  version: number
  exportedAt: string
  sourceVersion: string
  document: DocumentPackagePayload
}
