/**
 * UX-14.5.10.2 — the one, versioned shape an Asset export/import package
 * takes. Allow-list, not deny-list, exactly like `notePackageTypes.ts`
 * and `knowledgeNodePackageTypes.ts`: only the fields listed here can
 * ever leave an asset in a package. Deliberately excludes `id`,
 * `owner_id`, `workspace_id`, `original_path`/`optimized_path`/
 * `thumbnail_path` (internal storage references — never trusted or
 * reused on import; a fresh storage path is always generated by
 * `uploadAsset`), and any signed URL.
 *
 * Binary packaging decision (Option A — embed bytes, not Option B —
 * metadata-only + re-upload): chosen for portability (a package stays a
 * single, self-contained file, matching every other package type's own
 * invariant — "import" never becomes "create a row, then separately go
 * find the original file again"), security (the base64 payload never
 * executes; import decodes it into a `File` and routes it through the
 * exact same `uploadAsset` pipeline a manual upload already uses — same
 * MIME/size validation, same `createImageBitmap` decode-integrity
 * check, same derivative regeneration — so embedding bytes adds no new
 * attack surface), and existing infrastructure (zero new services: no
 * storage-to-storage copy, no edge function, fully client-side). Bounded
 * by the same `MAX_ASSET_UPLOAD_BYTES` cap the native upload path
 * already enforces (`validateAssetPackage.ts`), so a package can't grow
 * unbounded. This does not necessarily generalize to Documents (up to
 * 200MB per the UX-14.5.10 discovery) — that's a finding for the next
 * package type, not solved here.
 *
 * Only the *original* image's bytes ever travel — never `optimized_path`
 * or `thumbnail_path`. Those are derived content, and this framework's
 * existing rule (Notes' search index, Knowledge Nodes' canonical
 * identity) is that derived content always regenerates fresh on import,
 * never gets copied. `uploadAsset` regenerates both derivatives itself
 * from the imported original.
 *
 * Provenance gap (documented limitation, not a workaround): unlike Notes
 * and Knowledge Nodes, `assets` has no JSONB metadata column at all (see
 * `docs/ux-14.5.10-knowledge-exchange-expansion-discovery.md` §5), so an
 * imported asset cannot record an `importedFrom` block on the row
 * itself the way `generation_metadata.importedFrom` does for the other
 * two types. "No migrations" is a hard constraint this phase, so this
 * is accepted as an MVP limitation rather than worked around.
 */
export interface AssetPackagePayload {
  title: string
  /** MIME type as declared by the exporting account — informational only. `uploadAsset` independently revalidates against `SUPPORTED_IMAGE_MIME_TYPES` and decodes the actual bytes via `createImageBitmap`; a package that lies about this field fails validation/import on the real content, not on this claim. */
  mimeType: string
  /** Declared width/height/size — informational only, used solely for the import dialog's preview. The imported row's real values are always independently recomputed from the actual decoded bytes by `generateDerivatives` inside `uploadAsset`, never taken from the package. */
  width: number
  height: number
  sizeBytes: number
  /** The original image's own timestamp, preserved as inert metadata only — never used to set the imported row's own `created_at`, which reflects when *this account* actually received it. */
  createdAt: string
  /** Base64-encoded bytes of the *original* image only (never `optimized`/`thumbnail` — see this file's doc-comment). */
  fileDataBase64: string
}

export interface AssetPackage {
  version: number
  exportedAt: string
  sourceVersion: string
  asset: AssetPackagePayload
}
